[window]
opacity = 0.7
padding = { x = 100, y = 25 }
dynamic_padding = true
decorations = "Buttonless"
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
offset = { x = -2, y = -2 }
size = 16

[colors.primary]
foreground = "0xdfbf8e"
background = "0x282828"
