[window]
opacity = 0.6
padding = { x = 25, y = 25 }
#padding = { x = 750, y = 25 }
dynamic_padding = true
decorations = "Buttonless"
blur = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
offset = { x = -2, y = -2 }
size = 16

[colors.primary]
foreground = "0xdfbf8e"
background = "0x282828"
