# cc-tmux-status emoji config
# Customize emojis by editing this file.

EMOJI_SESSION_START="🌱"
EMOJI_USER_PROMPT_SUBMIT="🧠"
EMOJI_PRE_TOOL_USE="🚧"
EMOJI_POST_TOOL_USE="🧠"
EMOJI_POST_TOOL_USE_FAILURE="❌"
EMOJI_PERMISSION_REQUEST="🔓"
EMOJI_NOTIFICATION="🔔"
EMOJI_STOP="✅"
EMOJI_PRE_COMPACT="📦"
