-- vim.opt.number = true -- show line numbers
-- vim.opt.relativenumber = true -- show relative line numbers
vim.opt.foldmethod = "indent"
vim.opt.shiftwidth = 2 -- number of spaces to use for each step of (auto)indent
vim.opt.foldlevel = 99
vim.opt.confirm = true -- confirm to save changes before existing modified buffer
vim.opt.smartindent = true -- insert indents automatically
vim.opt.expandtab = true -- use spaces instead of tabs
vim.opt.tabstop = 2 -- number of spaces that a <Tab> in the file counts for
